//
// Created by goon on 08.04.2021.
//

#ifndef MOWERENGINE_CHECKERBOARDTEXTURE_H
#define MOWERENGINE_CHECKERBOARDTEXTURE_H


class CheckerBoardTexture {
};


#endif //MOWERENGINE_CHECKERBOARDTEXTURE_H
